// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using gmap.RouteResultJsonTypes;

namespace gmap.RouteResultJsonTypes
{

    public class Step
    {

        [JsonProperty("points")]
        public Point[] Points { get; set; }
    }

}
