// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using EANInterface.JsonNET.EANHotelListJsonTypes;

namespace EANInterface.JsonNET.EANHotelListJsonTypes
{

    internal class CachedSupplierResponse
    {

        [JsonProperty("@supplierCacheTolerance")]
        public string SupplierCacheTolerance { get; set; }

        [JsonProperty("@cachedTime")]
        public string CachedTime { get; set; }

        [JsonProperty("@supplierRequestNum")]
        public string SupplierRequestNum { get; set; }

        [JsonProperty("@supplierResponseNum")]
        public string SupplierResponseNum { get; set; }

        [JsonProperty("@supplierResponseTime")]
        public string SupplierResponseTime { get; set; }

        [JsonProperty("@candidatePreptime")]
        public string CandidatePreptime { get; set; }

        [JsonProperty("@otherOverheadTime")]
        public string OtherOverheadTime { get; set; }

        [JsonProperty("@tpidUsed")]
        public string TpidUsed { get; set; }

        [JsonProperty("@matchedCurrency")]
        public string MatchedCurrency { get; set; }

        [JsonProperty("@matchedLocale")]
        public string MatchedLocale { get; set; }
    }

}
