// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using EANInterface.JsonNET.EANHotelListJsonTypes;

namespace EANInterface.JsonNET.EANHotelListJsonTypes
{

    internal class ChargeableRateInfo
    {

        [JsonProperty("@averageBaseRate")]
        public string AverageBaseRate { get; set; }

        [JsonProperty("@averageRate")]
        public string AverageRate { get; set; }

        [JsonProperty("@commissionableUsdTotal")]
        public string CommissionableUsdTotal { get; set; }

        [JsonProperty("@currencyCode")]
        public string CurrencyCode { get; set; }

        [JsonProperty("@maxNightlyRate")]
        public string MaxNightlyRate { get; set; }

        [JsonProperty("@nightlyRateTotal")]
        public string NightlyRateTotal { get; set; }

        [JsonProperty("@grossProfitOffline")]
        public string GrossProfitOffline { get; set; }

        [JsonProperty("@grossProfitOnline")]
        public string GrossProfitOnline { get; set; }

        [JsonProperty("@surchargeTotal")]
        public string SurchargeTotal { get; set; }

        [JsonProperty("@total")]
        public string Total { get; set; }

        [JsonProperty("NightlyRatesPerRoom")]
        public NightlyRatesPerRoom NightlyRatesPerRoom { get; set; }

        [JsonProperty("Surcharges")]
        public Surcharges Surcharges { get; set; }
    }

}
