// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using EANInterface.JsonNET.EANHotelListJsonTypes;

namespace EANInterface.JsonNET.EANHotelListJsonTypes
{

    internal class HotelListResponse
    {

        [JsonProperty("customerSessionId")]
        public string CustomerSessionId { get; set; }

        [JsonProperty("numberOfRoomsRequested")]
        public int NumberOfRoomsRequested { get; set; }

        [JsonProperty("moreResultsAvailable")]
        public bool MoreResultsAvailable { get; set; }

        [JsonProperty("cacheKey")]
        public string CacheKey { get; set; }

        [JsonProperty("cacheLocation")]
        public string CacheLocation { get; set; }

        [JsonProperty("cachedSupplierResponse")]
        public CachedSupplierResponse CachedSupplierResponse { get; set; }

        [JsonProperty("HotelList")]
        public HotelList HotelList { get; set; }
    }

}
