// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using EANInterface.JsonNET.EANHotelListJsonTypes;

namespace EANInterface.JsonNET.EANHotelListJsonTypes
{

    internal class HotelSummary
    {

        [JsonProperty("@order")]
        public string Order { get; set; }

        [JsonProperty("@ubsScore")]
        public string UbsScore { get; set; }

        [JsonProperty("hotelId")]
        public int HotelId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("address1")]
        public string Address1 { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("stateProvinceCode")]
        public string StateProvinceCode { get; set; }

        [JsonProperty("postalCode")]
        public string PostalCode { get; set; }

        [JsonProperty("countryCode")]
        public string CountryCode { get; set; }

        [JsonProperty("airportCode")]
        public string AirportCode { get; set; }

        [JsonProperty("supplierType")]
        public string SupplierType { get; set; }

        [JsonProperty("propertyCategory")]
        public int PropertyCategory { get; set; }

        [JsonProperty("hotelRating")]
        public double HotelRating { get; set; }

        [JsonProperty("confidenceRating")]
        public int ConfidenceRating { get; set; }

        [JsonProperty("amenityMask")]
        public int AmenityMask { get; set; }

        [JsonProperty("tripAdvisorRating")]
        public double TripAdvisorRating { get; set; }

        [JsonProperty("tripAdvisorReviewCount")]
        public int TripAdvisorReviewCount { get; set; }

        [JsonProperty("tripAdvisorRatingUrl")]
        public string TripAdvisorRatingUrl { get; set; }

        [JsonProperty("locationDescription")]
        public string LocationDescription { get; set; }

        [JsonProperty("shortDescription")]
        public string ShortDescription { get; set; }

        [JsonProperty("highRate")]
        public double HighRate { get; set; }

        [JsonProperty("lowRate")]
        public double LowRate { get; set; }

        [JsonProperty("rateCurrencyCode")]
        public string RateCurrencyCode { get; set; }

        [JsonProperty("latitude")]
        public double Latitude { get; set; }

        [JsonProperty("longitude")]
        public double Longitude { get; set; }

        [JsonProperty("proximityDistance")]
        public double ProximityDistance { get; set; }

        [JsonProperty("proximityUnit")]
        public string ProximityUnit { get; set; }

        [JsonProperty("hotelInDestination")]
        public bool HotelInDestination { get; set; }

        [JsonProperty("thumbNailUrl")]
        public string ThumbNailUrl { get; set; }

        [JsonProperty("deepLink")]
        public string DeepLink { get; set; }

        [JsonProperty("RoomRateDetailsList")]
        public RoomRateDetailsList RoomRateDetailsList { get; set; }
    }

}
