// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using EANInterface.JsonNET.EANHotelListJsonTypes;

namespace EANInterface.JsonNET.EANHotelListJsonTypes
{

    internal class RateInfo
    {

        [JsonProperty("@priceBreakdown")]
        public string PriceBreakdown { get; set; }

        [JsonProperty("@promo")]
        public string Promo { get; set; }

        [JsonProperty("@rateChange")]
        public string RateChange { get; set; }

        [JsonProperty("RoomGroup")]
        public RoomGroup RoomGroup { get; set; }

        [JsonProperty("ChargeableRateInfo")]
        public ChargeableRateInfo ChargeableRateInfo { get; set; }

        [JsonProperty("nonRefundable")]
        public bool NonRefundable { get; set; }

        [JsonProperty("rateType")]
        public string RateType { get; set; }

        [JsonProperty("promoId")]
        public int PromoId { get; set; }

        [JsonProperty("promoDescription")]
        public string PromoDescription { get; set; }

        [JsonProperty("promoType")]
        public string PromoType { get; set; }

        [JsonProperty("currentAllotment")]
        public int CurrentAllotment { get; set; }

        [JsonProperty("HotelFees")]
        public HotelFees HotelFees { get; set; }
    }

}
