// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using EANInterface.JsonNET.EANHotelListJsonTypes;

namespace EANInterface.JsonNET.EANHotelListJsonTypes
{

    internal class Room
    {

        [JsonProperty("numberOfAdults")]
        public int NumberOfAdults { get; set; }

        [JsonProperty("numberOfChildren")]
        public int NumberOfChildren { get; set; }

        [JsonProperty("rateKey")]
        public string RateKey { get; set; }

        [JsonProperty("ChargeableNightlyRates")]
        [JsonConverter(typeof(SingleValueArrayConverter<ChargeableNightlyRate>))]
        public ChargeableNightlyRate[] ChargeableNightlyRates { get; set; }
    }

}
