// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using EANInterface.JsonNET.EANHotelListJsonTypes;

namespace EANInterface.JsonNET.EANHotelListJsonTypes
{

    internal class RoomRateDetails
    {

        [JsonProperty("roomTypeCode")]
        public int RoomTypeCode { get; set; }

        [JsonProperty("rateCode")]
        public int RateCode { get; set; }

        [JsonProperty("maxRoomOccupancy")]
        public int MaxRoomOccupancy { get; set; }

        [JsonProperty("quotedRoomOccupancy")]
        public int QuotedRoomOccupancy { get; set; }

        [JsonProperty("minGuestAge")]
        public int MinGuestAge { get; set; }

        [JsonProperty("roomDescription")]
        public string RoomDescription { get; set; }

        [JsonProperty("propertyAvailable")]
        public bool PropertyAvailable { get; set; }

        [JsonProperty("propertyRestricted")]
        public bool PropertyRestricted { get; set; }

        [JsonProperty("expediaPropertyId")]
        public int ExpediaPropertyId { get; set; }

        [JsonProperty("RateInfos")]
        public RateInfos RateInfos { get; set; }

        [JsonProperty("ValueAdds")]
        public ValueAdds ValueAdds { get; set; }
    }

}
