// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using gmap.RouteResultJsonTypes;

namespace gmap
{
    /// <summary>
    /// Represent result of direction search on google map
    /// </summary>
    public class RouteResult
    {

        [JsonProperty("routes")]
        public Route[] Routes { get; set; }
    }

}
